name: 'zephyr-ghcr'
on:
  workflow_dispatch:
  
jobs:
  zephyr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siliconlabs-massmarket/zephyr-env:latest:latest
      # If your repo is private, you may need credentials, see further below.
    steps:
      # The rest of your steps can assume the Zephyr environment is pre-installed
      - name: Build something
        run: |
          west --version
          pwd
          ls /opt
